window.latestNewsData = {
  generatedAt: "2026-06-11T16:55:00+08:00",
  mode: "editorial_bilingual_snapshot",
  selectionPolicy: "精选标准：优先选择最近24-48小时内能解释宏观数据、市场反应、央行政策、居民/企业影响、中国经济和能源/产业变化的新闻。",
  sources: [
    {
      name: "Associated Press",
      url: "https://apnews.com/article/878f6759c93fcb078aeefffe19d4dfa5",
      type: "financial_news",
    },
    {
      name: "MarketWatch",
      url: "https://www.marketwatch.com/livecoverage/cpi-report-today-live-updates/card/oil-prices-aren-t-bleeding-heavily-into-the-rest-of-the-economy-just-yet-tbfbH9NCP7ZfOxqSn0de",
      type: "markets",
    },
    {
      name: "The Wall Street Journal",
      url: "https://www.wsj.com/finance/stocks/global-stocks-markets-dow-news-06-10-2026-c106c317",
      type: "markets",
    },
    {
      name: "Investopedia",
      url: "https://www.investopedia.com/experts-see-some-good-news-in-the-cpi-report-but-inflation-still-carries-risks-for-markets-11994752",
      type: "financial_explainer",
    },
    {
      name: "U.S. Bureau of Labor Statistics",
      url: "https://www.bls.gov/news.release/cpi.nr0.htm",
      type: "official_data",
    },
    {
      name: "Bank of Canada",
      url: "https://www.bankofcanada.ca/2026/06/fad-press-release-2026-06-10/",
      type: "central_bank",
    },
    {
      name: "证券时报",
      url: "https://www.stcn.com/",
      type: "financial_news_cn",
    },
  ],
  items: [
    {
      cnTitle: "美国通胀升至4.2%，能源价格挤压家庭与企业",
      enTitle: "U.S. inflation rose to 4.2%, with energy costs squeezing households and businesses",
      source: "Associated Press",
      time: "2026-06-09 / 2026-06-10",
      url: "https://apnews.com/article/878f6759c93fcb078aeefffe19d4dfa5",
      cnSummary: "AP报道称，美国5月CPI同比升至4.2%，能源价格是主要推动因素。汽油、运输和企业成本上升正在改变居民消费和小企业经营决策。",
      enSummary: "AP reported that U.S. CPI rose 4.2% year over year in May, led mainly by energy prices. Higher fuel, transport and business costs are changing household spending and small-business decisions.",
      concepts: ["通胀", "能源价格", "居民实际收入", "企业成本"],
      impact: "这条新闻把宏观通胀和微观行为连接起来：价格冲击不仅改变CPI，也改变家庭预算、零售消费和企业用工。",
    },
    {
      cnTitle: "油价尚未大范围传导，但市场警惕二次通胀",
      enTitle: "Oil prices have not broadly bled into the economy yet, but markets are watching second-round inflation",
      source: "MarketWatch",
      time: "2026-06-10",
      url: "https://www.marketwatch.com/livecoverage/cpi-report-today-live-updates/card/oil-prices-aren-t-bleeding-heavily-into-the-rest-of-the-economy-just-yet-tbfbH9NCP7ZfOxqSn0de",
      cnSummary: "MarketWatch关注油价上涨是否会扩散到其他商品和服务。当前证据显示传导仍有限，但机票等部分项目已经出现压力。",
      enSummary: "MarketWatch focused on whether higher oil prices are spreading into other goods and services. Evidence of broad contagion remains limited, though some categories such as airfares show pressure.",
      concepts: ["二次传导", "核心通胀", "服务价格", "供给冲击"],
      impact: "这条新闻适合解释为什么央行不只看总体CPI，还要看能源冲击是否进入核心通胀。",
    },
    {
      cnTitle: "中东冲突与通胀担忧冲击市场，道指录得2026年最差单日表现",
      enTitle: "Middle East tensions and inflation fears hit markets, giving the Dow its worst day of 2026",
      source: "The Wall Street Journal",
      time: "2026-06-10",
      url: "https://www.wsj.com/finance/stocks/global-stocks-markets-dow-news-06-10-2026-c106c317",
      cnSummary: "WSJ报道称，中东局势推高油价，同时美国通胀数据削弱降息预期，美股、芯片股、黄金和美债收益率均出现明显波动。",
      enSummary: "The WSJ reported that Middle East tensions lifted oil prices while U.S. inflation data reduced hopes for rate cuts, triggering moves in stocks, semiconductors, gold and Treasury yields.",
      concepts: ["风险偏好", "贴现率", "油价冲击", "跨市场联动"],
      impact: "这条新闻展示一条宏观冲击如何同时影响股市、债市、黄金和商品价格。",
    },
    {
      cnTitle: "CPI报告中仍有积极信号：核心通胀较温和",
      enTitle: "The CPI report still had some good news: core inflation looked more contained",
      source: "Investopedia",
      time: "2026-06-10",
      url: "https://www.investopedia.com/experts-see-some-good-news-in-the-cpi-report-but-inflation-still-carries-risks-for-markets-11994752",
      cnSummary: "Investopedia指出，虽然总体通胀升至4.2%，但核心CPI月度涨幅较温和，这让投资者仍保留对股市反弹和年内政策转向的想象空间。",
      enSummary: "Investopedia noted that although headline inflation rose to 4.2%, monthly core CPI was relatively contained, leaving investors some room to hope for market resilience and a later policy shift.",
      concepts: ["核心CPI", "利率预期", "股票估值", "政策路径"],
      impact: "这条新闻提醒读者不要只看标题数字：核心通胀和市场预期差同样重要。",
    },
    {
      cnTitle: "美国官方CPI数据显示能源价格同比大涨",
      enTitle: "Official U.S. CPI data showed a sharp year-over-year rise in energy prices",
      source: "U.S. Bureau of Labor Statistics",
      time: "2026-06-10",
      url: "https://www.bls.gov/news.release/cpi.nr0.htm",
      cnSummary: "美国劳工统计局数据提供了今日学习的基准：总体CPI、能源分项和核心CPI共同决定市场如何理解通胀压力。",
      enSummary: "The BLS release provides the data anchor for today's lesson: headline CPI, energy components and core CPI together shape how markets interpret inflation pressure.",
      concepts: ["官方数据", "CPI", "能源分项", "核心CPI"],
      impact: "官方数据是其他媒体解读的源头，适合用来核对新闻叙事是否准确。",
    },
    {
      cnTitle: "加拿大央行维持政策利率在2.25%",
      enTitle: "Bank of Canada held its policy rate at 2.25%",
      source: "Bank of Canada",
      time: "2026-06-10",
      url: "https://www.bankofcanada.ca/2026/06/fad-press-release-2026-06-10/",
      cnSummary: "加拿大央行维持利率不变，为观察央行如何在通胀、增长和外部冲击之间权衡提供了对照案例。",
      enSummary: "The Bank of Canada kept its policy rate unchanged, offering a comparison case for how central banks balance inflation, growth and external shocks.",
      concepts: ["政策利率", "央行反应函数", "预期管理"],
      impact: "和美国通胀新闻放在一起看，可以训练你比较不同央行面对冲击时的政策约束。",
    },
    {
      cnTitle: "人民币升值并未明显拖累出口，汇率逻辑出现新变化",
      enTitle: "RMB appreciation has not obviously hurt exports, suggesting a changing exchange-rate story",
      source: "证券时报",
      time: "2026-06-11 06:50",
      url: "https://www.stcn.com/article/detail/3954718.html",
      cnSummary: "证券时报报道称，年初以来在岸人民币对美元逆势升值近3%，CFETS人民币汇率指数上涨近3.4%，但出口仍保持韧性。",
      enSummary: "Securities Times reported that the onshore RMB has appreciated nearly 3% against the dollar this year, while the CFETS RMB index is up about 3.4%, yet exports remain resilient.",
      concepts: ["汇率弹性", "贸易竞争力", "非价格竞争力"],
      impact: "这条新闻把学习视角从美国通胀扩展到中国外贸，说明汇率升值对出口的影响取决于产品结构和竞争力。",
    },
    {
      cnTitle: "八部门发文促进铁路旅游融合，扩大服务消费",
      enTitle: "Eight Chinese departments issued measures to integrate rail and tourism and expand services consumption",
      source: "证券时报",
      time: "2026-06-11 06:48",
      url: "https://www.stcn.com/article/detail/3954725.html",
      cnSummary: "商务部、文旅部、国铁集团等8部门发布措施，提出到2030年打造160列以上铁路旅游列车专用车组。",
      enSummary: "Eight departments, including the Ministry of Commerce and China State Railway Group, issued measures aiming to build more than 160 dedicated rail-tourism train sets by 2030.",
      concepts: ["服务消费", "供给创造需求", "产业政策", "社会资本"],
      impact: "这条新闻提供中国服务消费政策案例，适合解释政策如何通过改善供给场景来刺激需求。",
    },
  ],
};
